# Generated by Django 4.2.8 on 2024-01-17 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0003_remove_match_sedzia_match_sedziaa1_match_sedziaa2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='SedziaA1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szedziaa1_meczu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='SedziaA2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='szedziaa2_meczu', to=settings.AUTH_USER_MODEL),
        ),
    ]
