# Generated by Django 4.2.8 on 2024-01-17 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_alter_match_sedziaa1_alter_match_sedziaa2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='godzina',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='kolejka',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='miejscowosc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='rozgrywki',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='runda',
            field=models.CharField(choices=[('jesien', 'Jesienna'), ('wiosna', 'Wiosenna')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='ulica',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
