# Generated by Django 4.2.8 on 2023-12-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pytanie', models.CharField(max_length=1000)),
                ('poprawna_odpowiedz', models.CharField(max_length=10)),
            ],
        ),
    ]
