# Generated by Django 4.2.8 on 2023-12-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=500)),
                ('video_source', models.FileField(upload_to='video/%y')),
            ],
        ),
        migrations.DeleteModel(
            name='ViedoClip',
        ),
    ]
